apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc-hostpath 
spec:
  accessModes:
  - ReadWriteOnce
   storageClassName: localstorage
   resources:
      requests:
      storage: 1Gi